apiVersion: 1
datasources:
  - name: BackupHistory
    type: postgres
    uid: backuphistory
    url: postgres:5432
    user: report
    jsonData:
      database: backup_report
      sslmode: disable
    secureJsonData:
      password: report
    isDefault: false
    editable: false
